### ISSUE TITLE
No start.sh

### ISSUE THREAD

**Issue by AndrianD** [lspg/docker-ispconfig#1]
I think you forget to add the`start.sh` file somewhere, so the install cannot be achieved because of file not found.

**Comment by tonal-cuauhtli** [comment]
I am having the same issue, could not find start.sh at /usr/local/bin/

**Comment by annymosse** [comment]
if the following command so the issue is the command itself
```sh
$ docker create -name ispconfig -p 20:20 -p 21:21 -p 80:80 -p 443:443 -p 8080:8080 -p 53:53 -p 2222:22 lspg/ispconfig
$ docker start ispconfig
```
corrected:
```sh
$ docker create --name ispconfig -p 20:20 -p 21:21 -p 80:80 -p 443:443 -p 8080:8080 -p 53:53 -p 2222:22 lspg/ispconfig
$ docker start ispconfig
```

for Shell access also
```sh
$ docker exec -i -t lspg/ispconfig bash
```
corrected :
```sh
$ docker exec -i -t ispconfig bash
```
else that today is **07/03/2020** end i pull the image which there's no update since 3 years ago 
**lspg/ispconfig
By lspg • Updated 3 years ago
Debian based ISPConfig (latest is using Jessie 8.6)**

**Comment by ridoyes** [comment]
despite those corrections, http://your-ip:9001 and https://your-ip:8080  not worked?! 
 http://your-ip/webmail works but no have the congiguration on database and no password
 http://your-ip/phpMyAdmin works...

**Comment by lspg** [comment]
Really sorry guys, i'm not using ispconfig anymore as i'm now using a Synology and it does the job for my actual needs.
(I'm done with web dev indeed).
That's why i did not update the repo, to be honest, I'm just reading your comments, I haven't used github for a while.
my apologies, I hope you made it.
